import Head from 'next/head'
import { useRouter } from 'next/router'


function StatsGiocatori(props) {

    const router = useRouter();
    const fId = router.query.id

    const roleExtended = []
    roleExtended['P'] = 'Portiere'
    roleExtended['D'] = 'Difensore'
    roleExtended['C'] = 'Centrocampista'
    roleExtended['A'] = 'Attaccante'

    return (
        <div>
        <Head>
            <title>Statistiche Fantacalcio {props.player[0].name}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="pt-16">

            <div className="m-auto">
                <div className="hero rounded-md">
                    <div className="hero-content text-center">
                        <div className="w-full p-8">
                            <h1 className="text-3xl color-secondary-focus font-bold">{ props.player[0].name}</h1>
                            <div className="rating">
                                <input type="radio" name="rating-1" className="mask mask-star" />
                                <input type="radio" name="rating-1" className="mask mask-star" checked />
                                <input type="radio" name="rating-1" className="mask mask-star" />
                                <input type="radio" name="rating-1" className="mask mask-star" />
                                <input type="radio" name="rating-1" className="mask mask-star" />
                            </div>
                            <div>
                                Ruolo: { roleExtended[ props.player[0].role ] } → Squadra: { props.player[0].team }
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <section className="w-full text-center">
                <div className="stats shadow">
                    <div className="stat">
                        <div className="stat-figure text-accent">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="inline-block w-8 h-8 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path></svg>
                        </div>
                        <div className="stat-title">Fanta Media</div>
                        <div className="stat-value text-accent">{ props.player[0].mf }</div>
                        {/* <div className="stat-desc">21% more than last month</div> */}
                    </div>
                    
                    <div className="stat">
                        <div className="stat-figure text-secondary">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="inline-block w-8 h-8 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path></svg>
                        </div>
                        <div className="stat-title">Media Voto</div>
                        <div className="stat-value text-secondary">{ props.player[0].mv }</div>
                        {/* <div className="stat-desc">21% more than last month</div> */}
                    </div>
                    
                    <div className="stat">
                        <div className="stat-figure text-secondary">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="inline-block w-8 h-8 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path></svg>
                        </div>
                        <div className="stat-title">Partite giocate</div>
                        <div className="stat-value">{ props.player[0].mv }</div>
                        {/* <div className="stat-desc text-secondary">31 tasks remaining</div> */}
                    </div>
                </div>
            </section>

        </main>

        </div>
    )
}

export async function getStaticPaths() {
    const res = await fetch('http://127.0.0.1:8000/api/player-stats-data?limit=100')
    const players = await res.json()

    const paths = players.map(item => {
        return{
            params: {
                id: `${item.fid}`
            }
        }
    })

    return {
      paths: paths,
      fallback: true // false or 'blocking'
    };
}

export async function getStaticProps(context) {

    const { params } = context

    const res = await fetch('http://127.0.0.1:8000/api/single-player-stats-data/' + params.id)
    const player = await res.json()
    // console.log(player) // Non lo vedi nella console ma nel CMD dove esegui next

    return {
        props: {
            player: player
        }
    }
}
  


export default StatsGiocatori