import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero'

let formStyle = 'block'
let labelStyle = 'block text-xs tracking-widest uppercase mt-2 mb-1'
let inputStyle = 'block bg-white/25 p-3 w-full mb-4'
let textareaStyle = 'block bg-white/25 p-3 w-full mb-4 h-36'
let buttonStyle = 'btn btn-outline uppercase'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Contatti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="pt-16">
        <Hero 
          title="Contatti"
          desc=""
          btnLabel=""
          btnURL=""
        />
        <div className="bg-white/25 max-w-xl m-auto mt-24 p-8">
          <h2 className="text-xl font-black">Contattami</h2>
          <p className="text-sm mb-6">Lorem ipsum dolor sit amet</p>

          <form action="https://formspree.io/f/{form_id}" method="post" className={formStyle}>
            
            <label htmlFor="name" className={labelStyle}>Nome e Cognome</label>
            <input name="Name" id="name" type="text" placeholder="Nome e Cognome" className={inputStyle} />
            
            <label htmlFor="email" className={labelStyle}>Email</label>
            <input name="Email" id="email" type="email" placeholder="Email" className={inputStyle} />
            
            <label htmlFor="message" className={labelStyle}>Messaggio</label>
            <textarea name="Message" id="message" type="message" className={textareaStyle}  placeholder="Scrivi il tuo messaggio qui..."></textarea>

            <div className="flex">
              <div className="text-left w-1/2"></div>
              <div className="text-right w-1/2"><button type="submit" className={buttonStyle}>Invia</button></div>
            </div>
            
          </form>
        </div>

      </main>

    </div>
  )
}
